name: Greeting 

on: 
  push:
    branches:
       - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,16 * * *'

env:
  NOW_TIME: 23

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Set time to var NOW_TIME"
        run: echo "NOW_TIME=`date +%H`" >> $GITHUB_ENV 

      - name: "Check dont Work Time for exit"
        if: ${{ (env.NOW_TIME > 1) && (env.NOW_TIME < 6) }}
        run: exit 1

      - name: "Greetingi you have WORK time"
        run: |
          echo "$Greeting ${{github.actor}}. Time is $NOW_TIME hour !"
