name: Greeting 

on:
  workflow_dispatch

env:
  NOW_TIME: 23

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Set time to var NOW_TIME"
        run: echo "NOW_TIME=`date +%H`" >> $GITHUB_ENV 

      - name: "Check dont Work Time for exit"
        if: ${{ (env.NOW_TIME > 1) && (env.NOW_TIME < 6) }}
        run: exit 1

      - name: "Greetingi you have WORK time"
        run: |
          echo "$Greeting $First_Name. Time is $NOW_TIME !"
        env:
          First_Name: Petr 
