name: Злые эксперименты

on: 
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'


jobs:
       
  takeoff_attempt:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Get image nginx test
        run: docker pull nginx
          
      - name: Finish 
        run: echo "Run is OFF"
