name: Злые эксперименты

on: 
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'

jobs:
       
  check_time:
    if: ${{ github.head_ref }} == 'develop'
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Get Cuttent Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 2
          format: 'HH'
      
      - name: Set var    
        run: echo "TC=${{steps.time.outputs.time}}" >> $GITHUB_ENV
        
      - name: "Skip rest on sleep (non working) time (current hour is steps.time.outputs.time)"
        if: ${{env.TC}} == '0' || ${{env.TC}} == '1' || ${{env.TC}}  == '2' || ${{env.TC}}  == '3' || ${{env.TC}} == '4' || ${{env.TC}} == '5' 
        run: |
          echo "Skip rest because current hour (${{ env.TC }}) is inside sleep period of time"
          exit 2
