name: Злые эксперименты

on:
  workflow_dispatch:
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'
jobs:
  build_qa:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      chvar: ${{ steps.newvar.outputs.var1 }}
    
    steps:
    
      - name: Get image nginx test 1
        run: |
          docker pull nginx
    
      - name: Check event name
        id: newvar
        if: github.event_name == 'workflow_dispatch'
        run:  echo "::set-output name=var1::skip"
          
      - name: Echo
        if:  ${{ steps.newvar.outputs.var1 }} == 'skip'
        run: | 
          echo "Exit"
          exit 2
        
                 
  build_dev_or_stage:
    runs-on: ubuntu-latest
      
    steps:
      - name: Finish 
        run: echo "Run is OFF"

  Deploy:
    needs: [build_qa, build_dev_or_stage]
    runs-on: ubuntu-latest
      
    steps:
      - name: Finish Deploy QA
        if: ${{needs.build_qa.outputs.chvar}} != 'skip'
        run: echo "Deploy QA... No ${{needs.build_qa.outputs.chvar}} "
      
      - name: Finish Deploy for DEV or STAGE
        run: echo "Deploy DEV... OK"
