name: Злые эксперименты

on: 
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'


jobs:
       
  build:
    if: github.event_name == 'push'
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Get Cuttent Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 2
          format: 'HH'
      
      - name: Set var    
        run: echo "TC=${{steps.time.outputs.time}}" >> $GITHUB_ENV
        
      - name: Prepare -> docker login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: "Skip rest on sleep (non working) time current hour is ${{steps.time.outputs.time}}"
        #if: ${{ github.head_ref == 'main' && ( env.TC != '00' || env.TC != '01' || env.TC  != '02' || env.TC  != '03' || env.TC != '04' ) }} 
        run: |
          docker pull ghcr.io/vykenorse/api
          echo "!!!! Run this because current hour (${{ env.TC }}) is not inside sleep period of time"
          
      - name: Finish 
        run: echo "Run this because current hour (${{ env.TC }})"
