name: Злые эксперименты

on: 
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'

env:
  ACTION_SLEEP_BEGIN: 0
  ACTION_SLEEP_END: 5

jobs:
       
  check_time:
    if: ${{ github.head_ref }} == 'develop'
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Get Cuttent Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 2
          format: 'HH'

      - name: "Skip rest on sleep (non working) time (current hour is steps.time.outputs.time)"
        if: ${{ (steps.time.outputs.time == '1' ) && (steps.time.outputs.time == '2') && (steps.time.outputs.time == '3') && (steps.time.outputs.time == '4' ) && (steps.time.outputs.time == '5') }}
        run: |
          echo "Skip rest because current hour (${{ steps.time.outputs.time }}) is inside sleep period of time ( > ${{ env.ACTION_SLEEP_BEGIN }} and < ${{ env.ACTION_SLEEP_END }})"
          exit 2 
