name: Greeting 

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: 1 

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set time to var"
        run: echo `date +%d` 

        #- name: "Compere time"
        #if: $DATE_TIME => '13'
        #run: exit 1

      - name: "Say Hello Pert"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          date
        env:
          First_Name: Petr 
