name: Злые эксперименты

on: 
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get image nginx test 1
        run: docker pull nginx
    
      - name: STOP and exit
        if: ${ github.event_name == 'workflow_dispatch' }
          exit 2
          
      - name: Finish 
        run: echo "Run is OFF"
