name: Злые эксперименты

on:
  workflow_dispatch:
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'


jobs:
  build_1:
    runs-on: ubuntu-latest

    steps:
      - name: Get image nginx test 1
        run: docker pull nginx
    
      - name: STOP and exit
        if: github.event_name == 'workflow_dispatch'
        run: exit 2
         
  build_2:
    runs-on: ubuntu-latest
      
    steps:
      - name: Finish 
        run: echo "Run is OFF"

  Deploy:
    needs:[build_1, build_2]
    runs-on: ubuntu-latest

      
    steps:
      - name: Finish DEploy
        run: echo "Deploy..."
