name: Злые эксперименты

on:
  workflow_dispatch:
  push:
    branches:
       - main
         #schedule:
         # * is a special character in YAML so you have to quote this string
         #- cron:  '50 5,16 * * *'
env:
  VAR: 0


jobs:
  build_1:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      chvar: ${{ steps.newvar.outputs.var1 }}
    
    steps:
    
      - name: Get image nginx test 1
      - id: newvar
        run: |
          docker pull nginx
          echo "VAR=5" >> $GITHUB_ENV
          echo "::set-output name=var1::555"
    
      - name: STOP and exit
        if: github.event_name == 'workflow_dispatch'
        run: exit 2

      - name: Echo 
        run: echo "type Echo "
        
                 
  build_2:
    runs-on: ubuntu-latest
      
    steps:
      - name: Finish 
        run: echo "Run is OFF"

  Deploy:
    needs: [build_1, build_2]
    runs-on: ubuntu-latest

      
    steps:
      - name: Finish Deploy
        run: echo "Deploy... ${{needs.build_1.outputs.chvar}}"
