name: Greeting 

on:
  workflow_dispatch

env:
  START_SLEEP_TIME: 3
  STOP_SLEEP_TIME:  6
  NOW_TIME: 23

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Set time to NOW_TIME"
        run: echo "NOW_TIME=`date +%H`" >> $GITHUB_ENV 

      - name: "Check Time"
        if: ${{ (env.NOW_TIME > 13) || (env.NOW_TIME > 23) }}
        run: exit 1

      - name: "Greeting"
        run: |
          echo "$Greeting $First_Name. Time is $NOW_TIME !"
          date
        env:
          First_Name: Petr 
